import { Platform, StyleSheet } from "react-native";
import { leafyLogoColors } from "@/src/components/brand/RizomaLogo";
import { colors, radii, spacing, typography } from "@/src/theme/tokens";

/** Estilos compartidos login / register. */
export const authStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#E8F8EF",
  },
  root: {
    flex: 1,
    backgroundColor: "#E8F8EF",
  },
  decor: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  topBar: {
    zIndex: 2,
    paddingHorizontal: spacing.screenMargin + 6,
    paddingTop: 4,
    paddingBottom: 4,
    alignItems: "flex-start",
  },
  flex: {
    flex: 1,
    zIndex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.screenMargin + 10,
    paddingTop: 28,
    paddingBottom: 44,
  },
  scrollContentRegister: {
    flexGrow: 1,
    paddingHorizontal: spacing.screenMargin + 10,
    paddingTop: 8,
    paddingBottom: 44,
  },
  brandBlock: {
    alignItems: "center",
    marginBottom: 4,
  },
  medallionOuter: {
    marginBottom: 18,
    padding: 6,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255, 255, 255, 0.55)",
  },
  medallionOuterCompact: {
    marginBottom: 16,
    padding: 6,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255, 255, 255, 0.55)",
  },
  logoDisc: {
    height: 92,
    width: 92,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.brandSoft,
  },
  logoDiscCompact: {
    height: 86,
    width: 86,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.brandSoft,
  },
  wordmark: {
    fontSize: typography.hero + 6,
    lineHeight: typography.hero + 10,
    color: leafyLogoColors.wordmark,
    fontFamily: "Inter_800ExtraBold",
    letterSpacing: -1.2,
    textAlign: "center",
  },
  wordmarkCompact: {
    fontSize: typography.hero + 4,
    lineHeight: typography.hero + 8,
    color: leafyLogoColors.wordmark,
    fontFamily: "Inter_800ExtraBold",
    letterSpacing: -1.2,
    textAlign: "center",
  },
  tagline: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 16,
    lineHeight: 22,
    color: leafyLogoColors.leafDeep,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0.2,
  },
  screenHint: {
    marginTop: 6,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    color: colors.secondaryText,
    fontFamily: "Inter_400Regular",
  },
  formBlock: {
    marginTop: 32,
  },
  formBlockCompact: {
    marginTop: 28,
  },
  label: {
    marginBottom: 8,
    marginLeft: 4,
    fontSize: 12,
    lineHeight: 16,
    color: leafyLogoColors.wordmark,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  labelSpaced: {
    marginTop: 18,
  },
  labelSpacedCompact: {
    marginTop: 16,
  },
  inputShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: radii.xl,
    borderWidth: 1.5,
    borderColor: "rgba(229, 231, 235, 0.95)",
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    minHeight: 56,
  },
  inputShellFocused: {
    borderColor: colors.brand,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: colors.black,
    fontFamily: "Inter_500Medium",
    paddingVertical: Platform.OS === "ios" ? 14 : 12,
    includeFontPadding: false,
  },
  hint: {
    marginTop: 8,
    marginLeft: 4,
    fontSize: 12,
    lineHeight: 17,
    color: colors.grayText,
    fontFamily: "Inter_400Regular",
  },
  forgot: {
    alignSelf: "flex-end",
    paddingHorizontal: 2,
    paddingVertical: 8,
    marginTop: 4,
  },
  forgotText: {
    fontSize: 13,
    color: colors.brand,
    fontFamily: "Inter_600SemiBold",
  },
  errorBox: {
    marginTop: 12,
    borderRadius: radii.lg,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.2)",
  },
  errorText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.red,
    fontFamily: "Inter_500Medium",
  },
  ctaStack: {
    marginTop: 16,
  },
  socialPanel: {
    marginTop: 28,
    gap: 16,
    padding: 18,
    borderRadius: radii.xxl,
    backgroundColor: "#F2FBF6",
    borderWidth: 1,
    borderColor: "rgba(1, 183, 99, 0.08)",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 4,
  },
  dividerLine: {
    height: StyleSheet.hairlineWidth,
    flex: 1,
    backgroundColor: "rgba(10, 92, 58, 0.18)",
  },
  dividerLabel: {
    fontSize: 13,
    color: leafyLogoColors.leafDeep,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0.4,
  },
  authLinkRow: {
    marginTop: 36,
    minHeight: 48,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  authLinkLine: {
    textAlign: "center",
    fontSize: 15,
    lineHeight: 22,
  },
  linkMuted: {
    color: colors.secondaryText,
    fontFamily: "Inter_400Regular",
  },
  linkAccent: {
    color: colors.brand,
    fontFamily: "Inter_700Bold",
  },
  legal: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 12,
    lineHeight: 18,
    color: colors.grayText,
    fontFamily: "Inter_400Regular",
    paddingHorizontal: spacing.md,
  },
});
